#!system/bin/sh
echo Opening Whatsapp...
am start -n com.whatsapp.w4b/com.whatsapp.HomeActivity &&
echo Selecting first chat...
input keyevent 61 &&
input keyevent 66 &&
echo Writing text...
input text "$@" &&
echo Sending...
input keyevent 61 &&
input keyevent 61 &&
input keyevent 66 &&
#input keyevent 4
echo Reopening Termux...
monkey -p com.termux -v 1
